version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@4.0.1
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build_and_push_image:
          account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
          aws-access-key-id: "${AWS_ACCESS_KEY_ID}"
          aws-secret-access-key: "${AWS_SECRET_KEY}"
          region: "${AWS_REGION}"
          repo: batch
          tag: circleci
